package org.mjelle.quarkus.easynats;

import static org.assertj.core.api.Assertions.*;

import java.util.regex.Pattern;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class CloudEventsMetadataGeneratorTest {

  private CloudEventsMetadataGenerator generator;

  @BeforeEach
  void setUp() {
    generator = new CloudEventsMetadataGenerator();
  }

  // ISO 8601 pattern for validation
  private static final Pattern ISO_8601_PATTERN =
      Pattern.compile("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z");

  @Test
  void testGenerateIdReturnsValidUuidFormat() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, null, null, null);
    assertThat(metadata.id()).isNotNull().isNotBlank();
    assertThatNoException().isThrownBy(() -> java.util.UUID.fromString(metadata.id()));
  }

  @Test
  void testGenerateIdReturnsUniquIds() {
    CloudEventsMetadata metadata1 = generator.generate(TestClass.class, null, null, null);
    CloudEventsMetadata metadata2 = generator.generate(TestClass.class, null, null, null);
    assertThat(metadata1.id()).isNotEqualTo(metadata2.id());
  }

  @Test
  void testGenerateTimeReturnsValidIso8601Format() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, null, null, null);
    assertThat(metadata.time()).isNotNull().isNotBlank();
    assertThat(metadata.time()).matches(ISO_8601_PATTERN);
  }

  @Test
  void testGenerateTypeReturnsFullyQualifiedClassName() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, null, null, null);
    assertThat(metadata.type())
        .isEqualTo("org.mjelle.quarkus.easynats.CloudEventsMetadataGeneratorTest.TestClass");
  }

  @Test
  void testGenerateSourceReturnsNonEmptyString() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, null, null, null);
    assertThat(metadata.source()).isNotNull().isNotBlank();
  }

  @Test
  void testGenerateMetadataWithExplicitTypeAndSource() {
    CloudEventsMetadata metadata =
        generator.generate(TestClass.class, "com.example.Order", "/order-service", null);

    assertThat(metadata.specVersion()).isEqualTo("1.0");
    assertThat(metadata.type()).isEqualTo("com.example.Order");
    assertThat(metadata.source()).isEqualTo("/order-service");
    assertThat(metadata.dataContentType()).isEqualTo("application/json");
    assertThat(metadata.id()).isNotNull();
    assertThat(metadata.time()).isNotNull();
  }

  @Test
  void testGenerateMetadataWithNullTypeAutoGenerates() {
    CloudEventsMetadata metadata =
        generator.generate(TestClass.class, null, "/order-service", null);

    assertThat(metadata.type()).contains("TestClass");
    assertThat(metadata.source()).isEqualTo("/order-service");
  }

  @Test
  void testGenerateMetadataWithNullSourceAutoGenerates() {
    CloudEventsMetadata metadata =
        generator.generate(TestClass.class, "com.example.Order", null, null);

    assertThat(metadata.type()).isEqualTo("com.example.Order");
    assertThat(metadata.source()).isNotNull().isNotBlank();
  }

  @Test
  void testGenerateMetadataWithNullBothAutoGenerates() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, null, null, null);

    assertThat(metadata.type()).contains("TestClass");
    assertThat(metadata.source()).isNotNull().isNotBlank();
    assertThat(metadata.id()).isNotNull();
    assertThat(metadata.time()).isNotNull();
  }

  @Test
  void testGenerateMetadataIncludesAllRequiredFields() {
    CloudEventsMetadata metadata =
        generator.generate(TestClass.class, "com.example.Event", "/app", null);

    assertThat(metadata.specVersion()).isEqualTo("1.0");
    assertThat(metadata.type()).isNotNull();
    assertThat(metadata.source()).isNotNull();
    assertThat(metadata.id()).isNotNull();
    assertThat(metadata.time()).isNotNull();
    assertThat(metadata.dataContentType()).isEqualTo("application/json");
  }

  @Test
  void testGenerateMetadataSpecVersionIsAlways1dot0() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, "type", "source", null);

    assertThat(metadata.specVersion()).isEqualTo("1.0");
  }

  @Test
  void testGenerateMetadataDatacontentTypeIsAlwaysJson() {
    CloudEventsMetadata metadata = generator.generate(TestClass.class, "type", "source", null);

    assertThat(metadata.dataContentType()).isEqualTo("application/json");
  }

  @Test
  void testGenerateMetadataIdIsAlwaysAutoGenerated() {
    CloudEventsMetadata metadata1 = generator.generate(TestClass.class, "type", "source", null);
    CloudEventsMetadata metadata2 = generator.generate(TestClass.class, "type", "source", null);

    assertThat(metadata1.id()).isNotEqualTo(metadata2.id());
  }

  @Test
  void testGenerateMetadataTimeIsAlwaysAutoGenerated() {
    CloudEventsMetadata metadata1 = generator.generate(TestClass.class, "type", "source", null);
    CloudEventsMetadata metadata2 = generator.generate(TestClass.class, "type", "source", null);

    // Times should be different (unlikely to be exactly the same)
    assertThat(metadata1.time()).isNotEqualTo(metadata2.time());
  }

  // Helper test class
  static class TestClass {
    // Empty test class
  }
}
